// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Fira_Code } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Topbar from "./topbar";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const firaCode = Fira_Code({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // pick weights you need
  variable: "--font-fira-code",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${firaCode.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <Topbar />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
